@props(['img_path', 'class' => 'mb-4 aspect-square max-w-10 w-full rounded-lg transition-all ease-in-out bg-gray-200 object-cover group-hover:opacity-85 xl:aspect-[7/8]'])
@if (filter_var($img_path, FILTER_VALIDATE_URL))
    <!-- Display the fake image URL generated by Faker -->
    <img class="{{ $class }}"
        {{ $attributes }}
        src="{{ $img_path }}" alt="">
@else
    <!-- Display the image stored in storage -->
    <img class="{{ $class }}"
        {{ $attributes }}
        src="{{ Storage::url($img_path) }}" alt="">
@endif
